sonar.projectKey=laravel-sast-firmansyah
sonar.projectName=Laravel SAST - Firmansyah
sonar.projectVersion=1.0

sonar.sources=app,routes,config,database
sonar.tests=tests
sonar.language=php
sonar.php.version=8.1

sonar.exclusions=vendor/**,storage/**,public/vendor/**
sonar.test.inclusions=tests/**
sonar.sourceEncoding=UTF-8
