sonar.projectKey=laravel-sast-firmansyah
sonar.projectName=Laravel SAST - Firmansyah
sonar.projectVersion=1.0.0
sonar.projectDescription=Sample Laravel project with intentional vulnerabilities for SAST learning

sonar.sources=app,routes,database
sonar.tests=tests
sonar.language=php
sonar.php.version=8.1

sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/vendor/**
sonar.test.inclusions=tests/**/*.php
