sonar.projectKey=laravel-sast-firmansyah-fixed
sonar.projectName=Laravel SAST - Firmansyah (Remediated)
sonar.projectVersion=2.0.0
sonar.projectDescription=Laravel project after security remediation

sonar.sources=app,routes,database
sonar.tests=tests
sonar.language=php
sonar.php.version=8.1

sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/vendor/**
sonar.test.inclusions=tests/**/*.php
